language: python
sudo: required
services:
  - docker
install:
  - pip install pep8
  - pip install pylint
script:
  - pep8 --ignore=E123,E501 --show-source --show-pep8 run.py
  - pylint run.py
  - ./build.sh
